[package]
org= "ballerinax"
name= "googleapis.people"
version= "1.0.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["google", "people", "contact"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.people"

[build-options]
observabilityIncluded = true
